version: "2.0"
services:
  apache:
    image: qpos-apache:0.1
    container_name: quebase-apache-wangambura
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8600:80"
      - "865:443"
    volumes:
      - .:/var/www/html/
